### ISSUE TITLE
Provide a ES5 compatible distribution

### ISSUE THREAD

**Issue by YangsonHung** [bpmn-io/element-templates-validator#4]
我的项目中的webpack有es6检测，检测到node_modules有es6会报错，而我不能关掉这个配置，这是公司的脚手架。所以你能把这个包编译时都转为es5吗。
另外，现在这个包是0.3.0，而 bpmn-js-properties-panel 的依赖版本是0.2.0 ，那边能同步升级吗？

google translate:
The webpack in my project has es6 detection. If node_modules has es6, it will report an error, and I can't turn off this configuration. This is the company's scaffolding. So can you convert this package to es5 when compiling.
In addition, the package is now 0.3.0, and the dependency version of bpmn-js-properties-panel is 0.2.0, can I upgrade it simultaneously?

**Comment by pinussilvestrus** [comment]
Can you please format your issue to use [one of our templates](https://github.com/bpmn-io/element-templates-validator/issues/new/choose)? Without it, it will be hard for us to understand your use case/problem.

**Comment by nikku** [comment]
I've updated the issue description. What you'd love to see is a ES5 bundle of the tool. This has no priority for us at the moment.

**Comment by nikku** [comment]
We'll not do this. Instead we'd ask you to transpile this library to ES5 (i.e. via `babel`) if you'd like to use it in ES5 setups.
